name: traceconsumer CI workflow
on: [push]
env:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build project with Maven
      run: mvn -B compile --file pom.xml
  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Run all defined tests and generate war with Maven
      run: mvn -B verify --file pom.xml
    - run: ls ${GITHUB_WORKSPACE}/target/*.jar
    - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
    - name: Upload target folder
      uses: actions/upload-artifact@v2
        with:
        name: target
        path: |
          ${{ github.workspace }}/target
          ${{ github.workspace }}/reports

